### ISSUE TITLE
Animating Nodes

### ISSUE THREAD

**Issue by ahmed3esam** [AndrianBdn/GVR-SceneKit#4]
I tried to animate nodes using SCNAction & CABasicAnimation but the objects are not moving.
Do you have an idea about the reason of this issue?

**Comment by cwei** [comment]
Yes,

SceneKitVRRenderer passes always 0 to the rendering time.

            eyeRenderer.render(atTime: 0);

Try to pass the current time for the left eye and 0 for the right.

Viele Grüße
Carsten

**Comment by cwei** [comment]
See pull request #5

**Comment by AndrianBdn** [comment]
@ahmed3esam  I have just merged pull request that potentially could fix the problem.   @cwei  thank you once again

**Comment by ahmed3esam** [comment]
Perfect!
Animation is working as expected now, thanks for your effort @cwei @AndrianBdn
