### ISSUE TITLE
Hotspot support?

### ISSUE THREAD

**Issue by mudin3i** [AndrianBdn/GVR-SceneKit#6]
Hello!
Thank you for the awesome library!

I am wondering if there is hotspot support.

Thanks

**Comment by kgoedecke** [comment]
What are you trying to achieve? You can add what ever you want to the scene using scenekit.

**Comment by mudin3i** [comment]
I am trying to add hotspot into the scene. When the hotspot is clicked, it will change the scene (jump to other scene)

**Comment by AndrianBdn** [comment]
look at VRControllerSwift.swift it has some code related to cursor and events;
inside eventTriggered handler you can perform animation / change scene objects
