### ISSUE TITLE
When i try to change camera settings like field of view or focal length it's not applied to the scene also if i try to use orthographicScale property it's scaled for a couple of frames then everything returns to normal could you help me please 

### ISSUE THREAD

**Issue by sherifelgafary** [AndrianBdn/GVR-SceneKit#8]
When i try to change camera settings like field of view or focal length it's not applied to the scene also if i try to use orthographicScale property it's scaled for a couple of frames then everything returns to normal could you help me please

**Comment by AndrianBdn** [comment]
Hi, 

Camera projection and model view matrices are set (hardcoded) in SceneKitVRRenderer 

func cardboardView(_ cardboardView: GVRCardboardView!, draw eye: GVREye, with headTransform: GVRHeadTransform!)

if you want orthographic projection you will need to use different projection matrix. 

Possibly at that function you can also get some camera parameters and multiply matrices additionally to make them work.
